#!/bin/bash
# ==============================================================================
# KATANA MODULE: TOOLCHANGER
# Multi-Tool Support for Klipper
# ==============================================================================

function run_toolchanger_menu() {
    while true; do
        draw_header "KATANA TOOLCHANGER"
        echo ""
        echo "  [1] Quick Setup (Dual Extruder)"
        echo "  [2] ERCF Configuration"
        echo "  [3] Bondtech XTG Setup"
        echo "  [4] Custom Multi-Tool"
        echo "  [5] Tool Calibration"
        echo "  [B] Back"
        echo ""
        read -p "  >> COMMAND: " cmd
        
        case $cmd in
            1) quick_toolchanger_setup ;;
            2) setup_ercf ;;
            3) setup_bondtech_xtg ;;
            4) custom_toolchanger ;;
            5) tool_calibration ;;
            [bB]) return ;;
            *) log_error "Invalid selection." ;;
        esac
    done
}

function quick_toolchanger_setup() {
    draw_header "QUICK TOOLCHANGER SETUP"
    echo ""
    echo "  Select number of tools:"
    echo "  [2] Dual Extruder (2 tools)"
    echo "  [4] Quad Extruder (4 tools)"
    echo "  [6] Six Tool (6 tools)"
    echo "  [B] Back"
    echo ""
    read -p "  >> SELECT: " selection
    
    local num_tools=2
    case $selection in
        2) num_tools=2 ;;
        4) num_tools=4 ;;
        6) num_tools=6 ;;
        [bB]) return ;;
        *) log_error "Invalid selection."; return ;;
    esac
    
    log_info "Setting up $num_tools tools..."
    
    # Create toolchanger macros directory
    local macro_dir="$HOME/printer_data/config/macros/toolchanger"
    mkdir -p "$macro_dir"
    
    # Generate toolchange macros
    cat > "$macro_dir/ttool.gcode" << 'EOF'
[gcode_macro TTOOL]
description: Select tool T0-T{num_tools}
gcode:
    {% set tool = params.T|default(0)|int %}
    {% set tools = {num_tools} %}
    {% if tool >= tools %}
        { action_respond_info("Invalid tool number")}
    {% else %}
        T{tool}
        SET_GCODE_VARIABLE MACRO=TTOOL VARIABLE=current_tool VALUE={tool}
        { action_respond_info(f"Tool changed to T{tool}")}
    {% endif %}
EOF

    sed -i "s/{num_tools}/$num_tools/g" "$macro_dir/ttool.gcode"
    
    # Create individual tool macros
    for ((i=0; i<num_tools; i++)); do
        cat > "$macro_dir/t$i.gcode" << EOF
[gcode_macro T{$i}]
description: Select tool {$i}
gcode:
    T{$i}
    SET_GCODE_VARIABLE MACRO=TTOOL VARIABLE=current_tool VALUE={$i}
EOF
    done
    
    # Add to printer.cfg
    local cfg_file="$HOME/printer_data/config/printer.cfg"
    if ! grep -q "\[toolchanger\]" "$cfg_file" 2>/dev/null; then
        echo "" >> "$cfg_file"
        echo "# KATANA TOOLCHANGER CONFIG" >> "$cfg_file"
        echo "[toolchanger]" >> "$cfg_file"
        echo "tool_count: $num_tools" >> "$cfg_file"
    fi
    
    log_success "$num_tools tools configured!"
    echo "  Macros created in: $macro_dir"
    echo "  Use T0, T1, T2... to switch tools"
    
    read -p "  Press Enter..."
}

function setup_ercf() {
    draw_header "ERCF SETUP"
    echo ""
    echo "  Configuring ERCF (Enraged Rabbit Carrot Feeder)..."
    echo ""
    
    local ercf_dir="$HOME/printer_data/config/ercf"
    mkdir -p "$ercf_dir"
    
    # ERCF configuration file
    cat > "$ercf_dir/ercf_hardware.cfg" << 'EOF'
# ERCF Hardware Configuration
# Generated by KATANA

[ercf_servo ercf_servo]
pin: ERCF_SERVO_PIN
initial_angle: 0
max_angle: 180

[ercf_stepper stepper_e0]
step_pin: ERCF_STEP_PIN
dir_pin: ERCF_DIR_PIN
enable_pin: ERCF_ENABLE_PIN
microsteps: 16
rotation_distance: 22.678
endstop_pin: ^ERCF_ENDSTOP_PIN

[ercf_led led_status]
pin: ERCF_STATUS_LED
```

    log_success "ERCF config created at: $ercf_dir/ercf_hardware.cfg"
    echo "  Edit the pins according to your wiring!"
    
    read -p "  Press Enter..."
}

function setup_bondtech_xtg() {
    draw_header "BONTEX XTG SETUP"
    echo ""
    echo "  Configuring Bondtech XTG extruders..."
    echo ""
    
    local xtg_dir="$HOME/printer_data/config/macros/toolchanger"
    mkdir -p "$xtg_dir"
    
    # XTG Macro
    cat > "$xtg_dir/xtg_toolchange.gcode" << 'EOF'
[gcode_macro XTG_TOOL_CHANGE]
description: Bondtech XTG toolchange routine
gcode:
    {% set tool = params.T|int %}
    # Park current tool
    QUERY_ENDSTOPS
    # Select new tool
    T{tool}
    # Unlock gear
    SET_ERCF_SERVO ANGLE=160
    G4 P500
    # Move to new position (adjust for your setup)
    # Your custom positions here
    # Lock gear
    SET_ERCF_SERVO ANGLE=10
    G4 P300
    { action_respond_info(f"Tool changed to T{tool}")}
EOF

    log_success "XTG macros created!"
    
    read -p "  Press Enter..."
}

function custom_toolchanger() {
    draw_header "CUSTOM TOOLCHANGER"
    echo ""
    
    echo "  How many tools? (2-16)"
    read -p "  >> " num_tools
    
    if ! [[ "$num_tools" =~ ^[0-9]+$ ]] || [ "$num_tools" -lt 2 ] || [ "$num_tools" -gt 16 ]; then
        log_error "Invalid number (2-16)"
        return
    fi
    
    echo "  Tool switch method:"
    echo "  [1] Simple (T command only)"
    echo "  [2] Advanced (with parking)"
    echo "  [3] ERCF style"
    read -p "  >> " method
    
    local macro_dir="$HOME/printer_data/config/macros/toolchanger"
    mkdir -p "$macro_dir"
    
    case $method in
        1) # Simple
            for ((i=0; i<num_tools; i++)); do
                echo "[gcode_macro T$i]" > "$macro_dir/t$i.gcode"
                echo "gcode:" >> "$macro_dir/t$i.gcode"
                echo "    T$i" >> "$macro_dir/t$i.gcode"
            done
            ;;
        2) # Advanced
            for ((i=0; i<num_tools; i++)); do
                cat > "$macro_dir/t$i.gcode" << EOF
[gcode_macro T{$i}]
gcode:
    # Custom toolchange logic for T{$i}
    T{$i}
    # Add your parking/positioning here
EOF
            done
            ;;
        3) # ERCF style
            setup_ercf
            return
            ;;
    esac
    
    log_success "$num_tools tools configured with method $method!"
    read -p "  Press Enter..."
}

function tool_calibration() {
    draw_header "TOOL CALIBRATION"
    echo ""
    echo "  [1] Calibrate Z-Offset per Tool"
    echo "  [2] Calibrate Extrusion Ratio"
    echo "  [3] Calibrate Tool Offsets"
    echo "  [B] Back"
    echo ""
    read -p "  >> SELECT: " selection
    
    local macro_dir="$HOME/printer_data/config/macros/toolchanger"
    mkdir -p "$macro_dir"
    
    case $selection in
        1) # Z-Offset per tool
            cat > "$macro_dir/calibrate_z_offset.gcode" << 'EOF'
[gcode_macro CALIBRATE_Z_OFFSET]
description: Calibrate Z offset for each tool
gcode:
    {% for tool in range(0, 4) %}
    # Tool {tool}
    T{tool}
    G28 Z
    # Manual adjustment needed
    { action_respond_info(f"Adjust Z for Tool {tool}, then click Done")}
    # SAVE_OFFSET or manually add to config
    {% endfor %}
EOF
            log_success "Z-Offset calibration macro created"
            ;;
        2) # Extrusion ratio
            cat > "$macro_dir/calibrate_extrusion.gcode" << 'EOF'
[gcode_macro CALIBRATE_EXTRUSION]
description: Calibrate extrusion for each tool
gcode:
    {% for tool in range(0, 4) %}
    T{tool}
    # Mark filament at 100mm
    # Extrude 100mm
    # Measure actual extrusion
    # Calculate ratio
    {% endfor %}
EOF
            log_success "Extrusion calibration macro created"
            ;;
        3) # Tool offsets
            log_info "Use Klipper's DELAYED_GCODE or manual configuration"
            ;;
        [bB]) return ;;
    esac
    
    read -p "  Press Enter..."
}
